### ISSUE TITLE
Source texts

### ISSUE THREAD

**Issue by skochinsky** [keruiduo/SupplMatInfoRate#3]
Thank you for sharing this very interesting research.
Would it be possible to share the texts used?  For example, in Japanese the text length may depend on whether plain or polite speech was used and the lengths can be quite different, so it could be interesting to see if speech mode affects the information rate.

**Comment by keruiduo** [comment]
Dear Igor,

I'm very sorry for such a late reply. Of course we can share the texts. Here they are - they are actually reported in the supplementary materials of the paper in Science Advances, which I upload here.
[aaw2594_SM.pdf](https://github.com/keruiduo/SupplMatInfoRate/files/3830786/aaw2594_SM.pdf)

Have a nice day,

Christophe

**Comment by skochinsky** [comment]
Thank you!
